### ISSUE TITLE
Please share the scraped usernames

### ISSUE THREAD

**Issue by ghost** [Sid72020123/SUI-API#3]
Please can you share the list of usernames you've collected ever since starting this project?

I have a project of my own I want to do, optimal cloud variable compression, and my plan requires analysing the patterns seen across Scratchers' usernames. It would be a huge help to be able to start from 6million+ instead of from 0. Many thanks!

**Comment by Sid72020123** [comment]
I can share you but the data is too large for me to export and share. That's why I made the "/get_data" endpoint using which you can get a max. of 10k usernames per request and change the offset every time by 10k to get next 10k usernames.

**Note: The API is hosted on deta.space and doesn't work for now because of the new service limit enforced by the hosting provider. However, this is temporary and may get fixed soon...**

But in the version 1.2 of the API, I uploaded the data of 4.1M users indexed at that time. You can see that here in the "data" directory: https://github.com/Sid72020123/SUI-API/tree/86289e282b5f048516d7c5f5f84d701577860492

**Note: The API is down since 2-3 months so I can't guarantee that the data is updated.**

Maybe you can also try to get the followers of griffpatch using the official Scratch API...

**Comment by ghost** [comment]
Thank you!

**Comment by Sid72020123** [comment]
Closing this issue...
